---
# vars file for roles/docker


docker_packages_apt:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - python3-pip

docker_packages_yum:
  - yum-utils
  - device-mapper-persistent-data
  - lvm2
  - python3-pip

docker_engine:
  - docker-ce
  - docker-ce-cli
  - containerd.io

docker_gpg_apt: https://download.docker.com/linux/ubuntu/gpg

docker_gpg_yum: https://download.docker.com/linux/centos/gpg

docker_repo_apt: deb https://download.docker.com/linux/ubuntu bionic stable

docker_repo_yum: https://download.docker.com/linux/centos/docker-ce.repo

docker_image: nginx

container_name: my_nginx

container_port: '8080:80'

username_debian:
  - ubuntu

username_redhat:
  - ec2-user